### ISSUE TITLE
a SAS'15 paper

### ISSUE THREAD

**Issue by yuelee** [soundiness/soundiness.github.io#1]
Hi all,

Do you mind including our new SAS'15 paper titled "Effective Soundness-Guided Reflection Analysis" 

http://www.cse.unsw.edu.au/~jingling/papers/sas15.pdf

on your soundiness web site?

We will release our implementation soon at http://www.cse.unsw.edu.au/~corg/solar.

Thanks.

**Comment by too4words** [comment]
Hi Yue,

You should be able to make a pull request with that.

Ben

**Comment by yuelee** [comment]
Hi Ben,

Got it. Thanks.

Yue
